### ISSUE TITLE
ReconsumeLaterAsync : Asking for help.

### ISSUE THREAD

**Issue by wangshuyu** [fsharplang-ru/pulsar-client-dotnet#143]
`c#

var msg = await consumer.ReceiveAsync();
var body = Encoding.UTF8.GetString(msg.Data.ToArray());
if (msg.Properties.Count > 0)//retry
{
    //retry is error, What should I do here?
    _ = consumer.ReconsumeLaterAsync(msg, DateTimeToTimeStamp(DateTime.Now.AddSeconds(20)));
 }
else
{
    //success
    _ = consumer.ReconsumeLaterAsync(msg, DateTimeToTimeStamp(DateTime.Now.AddSeconds(10)));
}
`
以上代码,执行重试消息后, 会发生错误,这里我该如何处理呢?
想实现一个消息延时递增处理.
类似: 1s 5s 10s 30s .... 2h....10h

In the above code, after executing the retrial message, an error will occur. What should I do here?
Want to achieve a message delay incremental processing.
example: 1s 5s 10s 30s .... 2h....10h

**Comment by Lanayx** [comment]
Hi, @wangshuyu ! Can you please add the error details?

**Comment by wangshuyu** [comment]
> 嗨@wangshuyu！您能否添加错误详细信息？
第二次,推送重试 代码报错,提示存在一个messageid.
The second time, the push retrying code reports an error, indicating that there is a message ID


PulsarLogger[0]
      consumer(3, , -1) mailbox failure
      System.ArgumentException: An item with the same key has already been added. Key: RECONSUMETIMES
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at Pulsar.Client.Internal.DeadLetterProcessor`1.Pulsar.Client.Api.IDeadLetterProcessor<'T>.ReconsumeLater(Message`1 message, Int64 deliverAt, FSharpFunc`2 acknowledge)
         at <StartupCode$Pulsar-Client>.$ConsumerImpl.loop@646-212.Invoke(ConsumerMessage`1 _arg14)
         at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 405
         at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@303-8.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\mailbox.fs:line 303
         at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105

**Comment by wangshuyu** [comment]
> Hi, @wangshuyu ! Can you please add the error details?
@Lanayx 

 第二次,推送重试 代码报错,提示存在一个messageid. 谢谢您;
The second time, the push retrying code reports an error, indicating that there is a message ID.Thank you very much;


PulsarLogger[0]
consumer(3, , -1) mailbox failure
System.ArgumentException: An item with the same key has already been added. Key: RECONSUMETIMES
at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at Pulsar.Client.Internal.DeadLetterProcessor1.Pulsar.Client.Api.IDeadLetterProcessor<'T>.ReconsumeLater(Message1 message, Int64 deliverAt, FSharpFunc2 acknowledge)
at <StartupCode$Pulsar-Client>.$ConsumerImpl.loop@646-212.Invoke(ConsumerMessage1 _arg14) at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation1 ctxt, FSharpFunc2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 405 at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@303-8.Invoke(AsyncActivation1 ctxt) in F:\workspace_work\1\s\src\fsharp\FSharp.Core\mailbox.fs:line 303
at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105

**Comment by wangshuyu** [comment]
> Hi, @wangshuyu ! Can you please add the error details?
@Lanayx 

https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/4833eca1a2c95b047345d7325c1cd2670e55366a/src/Pulsar.Client/Internal/DeadLetters.fs
Code line number: 71 to 83 

相同messageid 执行多次ReconsumeLaterAsync错误
Error in reconsumelaterasync multiple times with the same message ID

**Comment by Lanayx** [comment]
Should be fixed in 1.8.4, please check

**Comment by wangshuyu** [comment]
@Lanayx  version 1.8.4 ,The problem has been resolved, thank Lanayx.
