### ISSUE TITLE
I didn't understand the pulsar retry queue

### ISSUE THREAD

**Issue by maliails** [fsharplang-ru/pulsar-client-dotnet#144]
hello，when I was in use pulsar.clinet, a problem in the line of the file: https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/4833eca1a2c95b047345d7325c1cd2670e55366a/src/Pulsar.Client/Internal/DeadLetters.fs ~ 72 line, 84, an error occurred
ERROR Log
` PulsarLogger[0]
      consumer(3, , -1) mailbox failure
      System.ArgumentException: An item with the same key has already been added. Key: RECONSUMETIMES
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at Pulsar.Client.Internal.DeadLetterProcessor`1.Pulsar.Client.Api.IDeadLetterProcessor<'T>.ReconsumeLater(Message`1 message, Int64 deliverAt, FSharpFunc`2 acknowledge)
         at <StartupCode$Pulsar-Client>.$ConsumerImpl.loop@646-212.Invoke(ConsumerMessage`1 _arg14)
         at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 405
         at <StartupCode$FSharp-Core>.$Mailbox.processFirstArrival@303-8.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\mailbox.fs:line 303
         at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105`

I can't use the Retry queue.

**Comment by Lanayx** [comment]
Should be fixed in 1.8.4, please check

**Comment by maliails** [comment]
> 应固定在1.8.4，请检查

Thank you !
