### ISSUE TITLE
Is serviceUrl Not supp domain

### ISSUE THREAD

**Issue by Micker5502** [fsharplang-ru/pulsar-client-dotnet#157]
**I using Pulsar.Client example to do testing. In CsharpExample run Task "RunSimple", I setting var serviceUrl with domain name.
Like:**
`const string serviceUrl = "pulsar://test.example.com:6650"`
**then start debug  and I get this error**
```
warn: PulsarLogger[0]
      GetPartitionedTopicMetadata failed will retry in 190 ms
      System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
         at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
         at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 86
         at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 79
         at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@45-33.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
      --- End of stack trace from previous location ---
         at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@42-34.Invoke(Exception _arg2)
         at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
         at FSharp.Control.Tasks.TaskBuilder.tryWith@174-1.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
      --- End of stack trace from previous location ---
         at FSharp.Control.Tasks.TaskBuilder.bindTaskConfigureFalse@131.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
info: PulsarLogger[0]
      Connecting to { LogicalAddress = LogicalAddress Unspecified/test.example.com:16650
  PhysicalAddress = PhysicalAddress Unspecified/test.example.com:16650 } with maxMessageSize: 5242880, brokerless: True
fail: PulsarLogger[0]
      Socket connection failed to Unspecified/test.example.com:16650
      System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
         at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
         at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 86
         at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 79
         at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@45-33.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
warn: PulsarLogger[0]
      GetPartitionedTopicMetadata failed will retry in 398 ms
      System.Net.Sockets.SocketException (11004): The requested name is valid, but no data of the requested type was found.
         at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
         at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.<GetResult>g__ThrowSocketException|10_0(SocketError e) in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 86
         at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 79
         at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@45-33.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
      --- End of stack trace from previous location ---
         at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@42-34.Invoke(Exception _arg2)
         at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
         at FSharp.Control.Tasks.TaskBuilder.tryWith@174-1.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
      --- End of stack trace from previous location ---
         at FSharp.Control.Tasks.TaskBuilder.bindTaskConfigureFalse@131.Invoke(Unit unitVar0)
         at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
```
**But I change serviceUrl to IP address it's work fine, Is this function do not support domain name?**

**Comment by Lanayx** [comment]
Hi, domain names are supported, you just need to set correct domain, not test.example.com

**Comment by Micker5502** [comment]
> Hi, domain names are supported, you just need to set correct domain, not test.example.com

Yes , test.example.com is sample. I using my own domain name , is not working.

**Comment by Lanayx** [comment]
Since it's a low level socket exception, not related to pulsar at all,  I'm afraid that I can't help much here. As [SO link suggests](https://stackoverflow.com/questions/29531253/the-requested-name-is-valid-but-no-data-of-the-requested-type-was-found-when) there is an issue with DNS.

**Comment by Micker5502** [comment]
> Since it's a low level socket exception, not related to pulsar at all, I'm afraid that I can't help much here. As [SO link suggests](https://stackoverflow.com/questions/29531253/the-requested-name-is-valid-but-no-data-of-the-requested-type-was-found-when) there is an issue with DNS.

ok , I will try to figure out by my self. Thx for reply
