### ISSUE TITLE
Client doesn't use all the service URLs specified.

### ISSUE THREAD

**Issue by Iezious** [fsharplang-ru/pulsar-client-dotnet#213]
```
var client = await new PulsarClientBuilder()
            .ServiceUrl("pulsar://10.110.20.34:6650,10.110.0.35:6650,10.110.0.36:6650")
            .BuildAsync();

var producer = await client.NewProducer()
                          .Topic("persistent://DATA/global/somedata")
                          .CompressionType(CompressionType.LZ4)
                          .EnableBatching(false)
                          .MaxPendingMessages(1000)
                          .MessageRoutingMode(MessageRoutingMode.RoundRobinPartition)
                          .CreateAsync();
```

The problem in the code above is that the first broker in the a list is wrong (we are emulating a prod fault when the broker is overloaded/temporary down/etc and haven't responded in a time). 

The expected behavior - the client is to try to connect to the next broker in a list.
The actual - it fails with the connect timeout exception.

**Comment by Lanayx** [comment]
Hi! Is there a stacktrace for timeout exception? I've made a fix, but wanted to make sure it's fixing the right thing

**Comment by Iezious** [comment]
> Hi! Is there a stacktrace for timeout exception? I've made a fix, but wanted to make sure it's fixing the right thing

```  at Pipelines.Sockets.Unofficial.Internal.Throw.Socket(Int32 errorCode) in /_/src/Pipelines.Sockets.Unofficial/Internal/Throw.cs:line 59
   at Pipelines.Sockets.Unofficial.SocketAwaitableEventArgs.GetResult() in /_/src/Pipelines.Sockets.Unofficial/SocketAwaitableEventArgs.cs:line 82
   at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@41-29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@41-29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <StartupCode$Pulsar-Client>.$ConnectionPool.clo@130-30.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at <StartupCode$Pulsar-Client>.$BinaryLookupService.catchHandler@1(BinaryLookupService this, String topicName, Int32 remainingTimeMs, DnsEndPoint endpoint, Backoff backoff, Exception _arg4)
   at <StartupCode$Pulsar-Client>.$BinaryLookupService.GetPartitionedTopicMetadataInner@27-13.Invoke(Exception exn)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallFilterThenInvoke[T](AsyncActivation`1 ctxt, FSharpFunc`2 filterFunction, ExceptionDispatchInfo edi) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 500
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 105
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <StartupCode$Pulsar-Client>.$BinaryLookupService.GetPartitionedTopicMetadata@47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at <StartupCode$Pulsar-Client>.$PulsarClient.CreateProducerAsync@262.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<<<Main>$>g__StarPublish|0_0>d.MoveNext() in C:\Projects\Communication.Pulsar\Tests\Program.cs:line 26
```

**Comment by Lanayx** [comment]
Thanks! This means that the fix should help, I'll publish the new version soon

**Comment by Lanayx** [comment]
https://www.nuget.org/packages/Pulsar.Client/2.10.4 please verify

**Comment by Lanayx** [comment]
Closing as abandoned
